import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_us': {

            'Login': "Login",
            'Send': 'Send',

            "Send ": "Send ",
            "Request": "Request",
            'Transactions': "Transactions",
            'Logout': "Logout",
            'Back': "Back ",
            "Don't have an account? ": "Don't have an account?",
            'enter amount here': "enter amount here",
            'Balance': "Balance",
            'pin number': "pin number",
            "Enter 6 digits pin": "Enter 6 digits pin",
            'pin': "pin",
            "Register": "Register",
            "Enter nick name": "Enter nick name",
            "See More": "See More",
           
            "Profile": "Profile",
          
            "User Name": "User Name",
            "Full Name": "Full Name",
           
            "Upi id": "Upi Id",
            "Delete Account": "Delete Account",
            "Enter Your Pin": "Enter Your Pin",
            "Current Balance": "Current Balance",
            "enter upi id": "enter upi id",
            "enter recevier name": "enter recevier name",
            "selected language": "you have selected english",
            "going to money sending page": "going to money sending page",
            "going to login page": 'going to login page',
            "going to back page": "going to back page",
            'going to register page': 'going to register page',
            'going to home page': 'going to home page',
            'going to profile page': 'going to profile page',
            'your personal details are': 'your personal details are',
            'your full name is': 'your full name is',
            'Full Name': 'full name',
            'Mobile': 'mobile',
            'Upi id': 'upi id',
            'update profile': 'update profile',
            'Sorry command not recognized try again':
                'Sorry command not recognized try again',
            'you have entered incorrect password':
                'you have entered incorrect password',
            "You are successfully logged in": 'You are successfully logged in',
            "Success": 'Success',
            'Failed': 'Failed',
            'Incorrect Password': 'Incorrect Password',
            'No user Exists with nick name': 'No user Exists with nick name',
            'please check your pin': 'please check your pin',
            'your account balance is ruppess': 'your account balance is ruppess',
            'profile': 'profile',
            'send money to': 'send money to',
            'say your name': 'say your name',
            'your transaction details': 'your transaction details',
            'write your pin': 'write your pin',
            'login to check your balance': 'login to check your balance',
            'update': 'update',
            'edit': 'edit',
            'new': 'new',
            
           
            'Transactions': 'transactions',
            'Received from': 'Received from',
            'Money sent to': 'Money sent to',
            'Empty input': 'empty input',
            'Log out': 'Log out',
            'You have logged out': 'you have logged out',
            'Updated successfully': 'updated successfully',
            'Commands Guide': 'Commands Guide',
            'enter': 'enter',
           
            'This information will be securely saved as per the RP Bank Terms of Services and Privacy Policy.':'This information will be securely saved as per the RP Bank Terms of Services and Privacy Policy.',
            
            'Create Account': 'Create Account',
            'Enter amount': 'Enter amount',
            'Next': 'Next',
            'Already have an account?': 'Already have an account?',
            'How to use': 'How to use',
            'des1':
                'Long press on the mic icon with red circle on the bottom of screen.',
            'des2':
                'After long press you will hear an sound.After that sound say your command.',
            'des3':
                'After saying your command you will hear sound again.Ater that sound effect remove long press',
            'des4':
                'Ater removing the finger from mic,if your command exists it will perform the action,if not repeat the above steps with different command'
          },
      
        'te_IN': {
            'Enter mobile number':'మొబైల్ నంబర్‌ను నమోదు చేయండి',
           'Send feedback':'అభిప్రాయాన్ని పంపండి',
           'Language changed':'భాష మార్చబడింది',
            'Refresh':'రిఫ్రెష్',
             "Enter full name":'పూర్తి పేరును నమోదు చేయండి',
            'Enter Bank Details':'బ్యాంకు వివరాలను నమోదు చేయండి',
            'Account number':'ఖాతా సంఖ్య',
            'Re-enter account number':'ఖాతా సంఖ్యను మళ్లీ నమోదు చేయండి',
            'IFSC':'ఐ ఎఫ్ ఎస్ సి',
             'Delete':'తొలగించు',
            'Search for IFSC':'ఐ ఎఫ్ ఎస్ సి కోసం శోధించండి',
            'Recipient name':'గ్రహీత పేరు',
            'Continue':'కొనసాగించు',
           'Set Pin':'పిన్ సెట్ చేయండి',
            "Enter user name":'వినియోగదారు పేరును నమోదు చేయండి',
            'No user found with the name':'పేరుతో వినియోగదారు కనుగొనబడలేదు',
          // kkkkk
          'Enter your 6 digits pin': 'మీ ఆరు అంకెల పిన్‌ను నమోదు చేయండి',
          'Bank transfer': 'బ్యాంకు బదిలీ',
          'Send to person': 'వ్యక్తికి పంపండి',
          'UPI': 'యు పి ఐ',
          'Transfer money':'డబ్బు బదిలీ చేయండి',
          'Account balance': 'ఖాతా నిలువ',
          'People': 'వ్యక్తులు',
          'Features': 'లక్షణాలు',
          'Featured':'లక్షణాలు',
          'Explore': 'అన్వేషించండి',
          'Flight Tickets': 'విమాన టికెట్లు',
          'Bus Tickets': 'బస్సు టిక్కెట్లు',
          'Train ticket': 'రైలు టికెట్',
          'Movie tickets': 'సినిమా టిక్కెట్లు',
          'Event tickets': 'ఈవెంట్ టిక్కెట్లు',
          'Hotels': 'హోటళ్ళు',
          'Toll': 'టోల్',
          'Uber cabs': 'ఉబెర్ క్యాబ్‌లు',
          'Tickets booking': 'టిక్కెట్లు బుకింగ్',
          'Stocks and IPO': 'స్టాక్స్ మరియు IPO',
          'Insurance': 'భీమా',
          'healthcare': 'ఆరోగ్య సంరక్షణ',
          'Travel': 'ప్రయాణం',
          'Promotions': 'ప్రమోషన్లు',
          'Rewards': 'బహుమతులు',
          'Offers': 'ఆఫర్లు',
          'Step':'దశ',
          'Refferals': 'రెఫరల్స్',
          'See all payment activities': 'అన్ని చెల్లింపు కార్యకలాపాలను చూడండి',
          'Invite your friends': 'మీ స్నేహితులను ఆహ్వానించండి',
          "Get ₹101 after each friend's first payment":
              "ప్రతి స్నేహితుని మొదటి చెల్లింపు తర్వాత 101 రూపాయలను పొందండి",
          'Invite': 'ఆహ్వానించండి',
          'All transactions': 'అన్ని లావాదేవీలు',
          'Paying to': 'కు చెల్లిస్తోంది',
          'Pay to':"చెల్లించాలి",
          "Update":'నవీకరణ',
          "Enter new":'కొత్తగా నమోదు చేయండి',
          'Enter new mobile  number':'కొత్త మొబైల్ నంబర్‌ను నమోదు చేయండి',
          'Enter new UPI ID':'కొత్త యుపిఐ ఐడిని నమోదు చేయండి',
          'Enter new full name':'కొత్త పూర్తి పేరును నమోదు చేయండి',
          'Enter new user name':'కొత్త వినియోగదారు పేరును నమోదు చేయండి',
          'Enter new nick name':'కొత్త మారుపేరును నమోదు చేయండి',
          'your account has been deleted':'మీ ఖాతా తొలగించబడింది',
          'Paid to' :'కు చెల్లించారు',
          'try again':'మళ్ళీ ప్రయత్నించండి',
          'Recevied to you':'మీకు అందింది',
          'What is this for?': 'ఇది ఎందుకు?',
          'Tap to speak': 'మాట్లాడటానికి నొక్కండి',
          'You Earned Cashback':'మీరు క్యాష్‌బ్యాక్ పొందారు',
          'Oops!! try next ':'అయ్యో!! తదుపరిసారి ప్రయత్నించండి',
          'Scratch the above card for your reward':'మీ రివార్డ్ కోసం పై కార్డ్‌ని స్క్రాచ్ చేయండి',
          'Payment successful': 'చెల్లింపు విజయవంతమైంది',
          'This information will be securely saved as per the RP Bank Terms of Services and Privacy Policy.':'ఆర్ పి బ్యాంక్ సేవా నిబంధనలు మరియు గోప్యతా విధానం ప్రకారం ఈ సమాచారం సురక్షితంగా సేవ్ చేయబడుతుంది.',
          'Done': 'సరే',
          'Say hello': 'హలో చెప్పండి',
          'Pay': 'చెల్లించండి',
          'Write to UPI': 'యూపీఐ కి వ్రాయండి',
          'Account': 'ఖాతా',
          'Set profile photo':'ప్రొఫైల్ ఫోటోను సెట్ చేయండి',
          'Take photo':'ఫోటో తీసుకో',
          'Choose photo':'ఫోటోను ఎంచుకోండి',
          'Signed in as': 'ఇలా సైన్ ఇన్ చేసారు:',
          'Mobile number': 'మొబైల్ నంబర్',
          'Payment methods': 'చెల్లింపు పద్ధతులు',
          'Language': 'భాష',
          'App Theme': 'యాప్ థీమ్',
          'PRIVACY AND SECURITY': 'గోప్యత మరియు భద్రత',
          'Privacy': 'గోప్యత',
          'Notifications': 'నోటిఫికేషన్లు',
          'Security': 'భద్రత',
          'Log out': 'లాగ్ అవుట్',
          'Log out from RP Bank': ' బ్యాంక్ నుండి లాగ్ అవుట్ అవ్వండి',
          'Close account': 'ఖాతాను మూసివేయండి',
          'Clear RP Bank profile on this device':
              'ఈ పరికరంలో ఆర్ పి బ్యాంక్ ప్రొఫైల్‌ను క్లియర్ చేయండి',
          'INFORMATION': 'సమాచారం',
          'Help & feedback': 'సహాయం మరియు అభిప్రాయం',
          "PERSONAL DETAILS":'వ్యక్తిగత వివరాలు',
          'Terms & privacy policy': 'నిబంధనలు మరియు గోప్యత',
          'Enter recipient name': 'గ్రహీత పేరు నమోదు చేయండి',
          'Exit App':'అప్లికేషన్ నుండి నిష్క్రమించు',
          'Do you want to exit the app':'మీరు యాప్ నుండి నిష్క్రమించాలనుకుంటున్నారా',
          'Yes':'అవును',
          'No':'కాదు',
          'Update':'నవీకరించు',


          'Recents': 'ఇటీవలివి',
          'success': 'విజయం',
          'Money successfully sent to ':
              'డబ్బు విజయవంతంగా పంపబడింది',
          'Profile': 'ప్రొఫైల్',
          'Morning': 'శుభోదయం',
          'Good afternoon': 'శుభ మద్యాహ్నం',
          'Good evening': 'శుభ సాయంత్రం',
          'Developed By':' ద్వారా అభివృద్ధి చేయబడింది',
          'Sai Kumar Kusangi and Sravika Malipeddi':'సాయి కుమార్ కుసంగి మరియు శ్రావిక మలిపెద్ది',
// kkkkk
          'Your full name is': 'మీ పూర్తి పేరు',
          'Your user name is':'మీ వినియోగదారు పేరు',
          'Enter': 'ఎంటర్',
          'Transactions': 'లావాదేవీలు',
          'Send': 'పంపండి',
          'Login': "ప్రవేశించండి",
          "Nick name": "మారుపేరు",
          "Good Morning": "శుభోదయం",
          "Good Afternoon": "శుభ మద్యాహ్నం",
          "Good Evening": "శుభ సాయంత్రం",
          "Send ": "పంపండి",
          'Request': 'అభ్యర్థన',
          "Don't have an account? ": "ఖాతా లేదా?",
          "Register": "నమోదు చేసుకోండి",
          "Enter 6 digits pin": "6 అంకెల పిన్‌ని నమోదు చేయండి",
          "Transactions": "లావాదేవీలు",
          "Enter nick name": "మారుపేరును నమోదు చేయండి",
          "Balance": "సంతులనం",
          "See More": "ఇంకా చూడండి",
          "Profile": "ప్రొఫైల్",
          "User name": "వినియోగదారు పేరు",
          "Full name": "పూర్తి పేరు",
          "UPI Id": "యు పి ఐ ఐ డి",
          "Delete account": "ఖాతాను తొలగించండి",
          "Enter your pin": "మీ పిన్‌ని నమోదు చేయండి",
          "Current Balance": "ప్రస్తుత నిల్వ",
          "Enter upi id": "యూపీఐ ఐడి ని నమోదు చేయండి",
          "Enter recevier name": "రిసీవియర్ పేరు నమోదు చేయండి",
          "Selected language": "మీరు తెలుగును ఎంచుకున్నారు",
          "Going to money sending page": "డబ్బు పంపే పేజీకి వెళుతోంది",
          'Going to login page': "లాగిన్ పేజీకి వెళుతోంది",
          "Going to back page": "పేజీ వెనుకకు వెళుతోంది",
          'Going to register page': "నమోదు పేజీకి వెళుతోంది",
          'Going to home page': 'హోమ్ పేజీకి వెళుతోంది',
          'Going to profile page': "ప్రొఫైల్‌పేజీకి వెళుతోంది",
          'Go to home page':'హోమ్ పేజీకి వెళ్లండి',
          'Go to profile page':'ప్రొఫైల్ పేజీకి వెళ్లండి',
          'Check balance':'సంతులనం',
          'See history':'లావాదేవీలను చూపించు',
          'Send money':'డబ్బు పంపండి',
          'Try saying':'చెప్పడానికి ప్రయత్నించండి',
          'Your personal details are': 'మీ వ్యక్తిగత వివరాలు',
          'Full name': 'పూర్తి పేరు',
          'Mobile': 'మొబైల్',
          'UPI ID': 'యూ పీ ఐ ఐ డి',
          'Update profile': 'నవీకరణ',
          'Sorry command not recognized try again':
              "క్షమించండి ఆదేశం గుర్తించబడలేదు మళ్లీ ప్రయత్నించండి",
          'You have entered incorrect password':
              'మీరు తప్పు పాస్‌వర్డ్‌ని నమోదు చేసారు',
          "You are successfully logged in": "మీరు విజయవంతంగా లాగిన్ అయ్యారు",
          "Success": 'విజయం',
          'Failed': 'విఫలమైంది',
          'Incorrect Password': 'సరికాని పాస్వర్డ్',
          'No user Exists with nick name':
              'మారుపేరుతో వినియోగదారు నిష్క్రమించలేదు',
          'Please check your pin': 'దయచేసి మీ పిన్‌ని తనిఖీ చేయండి',
          'Your account balance is ruppess': 'మీ ఖాతా బ్యాలెన్స్ రూపాయలు',
          'Profile': 'ప్రొఫైల్',
          'Send money to': 'డబ్బు పంపండి',
          'Say your name': 'మీ పేరు చెప్పండి',
          'Write your pin': 'మీ పిన్ వ్రాయండి',
          'Your transaction details': 'మీ లావాదేవీ వివరాలు',
          'Log in to check your balance':
              'మీ బ్యాలెన్స్ తనిఖీ చేయడానికి లాగిన్ చేయండి',
          'Update': 'నవీకరణ',
          'Edit': 'సవరించు',
          'New': 'కొత్త',
          'Long press to try again':'మళ్లీ ప్రయత్నించడానికి ఎక్కువసేపు నొక్కండి',
          'Received from': 'నుండి స్వీకరించబడింది',
          'Money sent to': 'డబ్బు పంపబడింది',
          'Empty input': 'ఖాళీ ఇన్‌పుట్',
          'Log out': 'లాగ్ అవుట్',
          'You have logged out': 'మీరు లాగ్ అవుట్ చేసారు',
          'Updated successfully': 'విజయవంతంగా నవీకరించబడింది',
          'Commands Guide': 'మార్గ దర్శకులు',
          'Create Account': 'ఖాతాను సృష్టించండి',
          'Next': 'తరువాత',
          "Enter amount": 'మొత్తాన్ని నమోదు చేయండి',
          'Already have an account?': 'ఖాతా కలిగి ఉన్నారా?',
          'How to use': 'ఎలా ఉపయోగించాలి',
          'Something went wrong':'ఎక్కడో తేడ జరిగింది',
          'Failed':'విఫలమయ్యారు',
          'des1':
              'స్క్రీన్ దిగువన ఎరుపు వృత్తంతో మైక్ చిహ్నంపై ఎక్కువసేపు నొక్కండి.',
          'des2':
              'ఎక్కువసేపు నొక్కిన తర్వాత మీకు శబ్దం వినబడుతుంది. ఆ ధ్వని తర్వాత మీ ఆదేశాన్ని చెప్పండి.',
          'des3':
              'మీ కమాండ్‌ని చెప్పిన తర్వాత మీకు మళ్లీ సౌండ్ వినబడుతుంది. ఆ సౌండ్ ఎఫెక్ట్ తర్వాత లాంగ్ ప్రెస్‌ని తీసివేయండి.',
          'des4':
              'ఆటర్ మైక్ నుండి వేలును తీసివేస్తుంది. మీ కమాండ్ నిష్క్రమిస్తే అది చర్యను అమలు చేస్తుంది, కాకపోతే మళ్లీ వేరే ఆదేశంతో పై దశలను పునరావృతం చేయండి.'
        }
      };
}
