import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_us': {

            'Login': "Login",
            'Send': 'Send',

            "Send ": "Send ",
            "Request": "Request",
            'Transactions': "Transactions",
            'Logout': "Logout",
            'Back': "Back ",
            "Don't have an account? ": "Don't have an account?",
            'enter amount here': "enter amount here",
            'Balance': "Balance",
            'pin number': "pin number",
            "Enter 6 digits pin": "Enter 6 digits pin",
            'pin': "pin",
            "Register": "Register",
            "Enter nick name": "Enter nick name",
            "See More": "See More",
            "Profile": "Profile",
            "User Name": "User Name",
            "Full Name": "Full Name",
            "Upi id": "Upi Id",
            "Delete Account": "Delete Account",
            "Enter Your Pin": "Enter Your Pin",
            "Current Balance": "Current Balance",
            "enter upi id": "enter upi id",
            "enter recevier name": "enter recevier name",
            "selected language": "you have selected english",
            "going to money sending page": "going to money sending page",
            "going to login page": 'going to login page',
            "going to back page": "going to back page",
            'going to register page': 'going to register page',
            'going to home page': 'going to home page',
            'going to profile page': 'going to profile page',
            'your personal details are': 'your personal details are',
            'your full name is': 'your full name is',
            'Full Name': 'full name',
            'Mobile': 'mobile',
            'Upi id': 'upi id',
            'update profile': 'update profile',
            'Sorry command not recognized try again':
                'Sorry command not recognized try again',
            'you have entered incorrect password':
                'you have entered incorrect password',
            "you are successfully logged in": 'you are successfully logged in',
            "Success": 'Success',
            'Failed': 'Failed',
            'Incorrect Password': 'Incorrect Password',
            'No user Exits with nick name': 'No user Exits with nick name',
            'please check your pin': 'please check your pin',
            'your account balance is ruppess': 'your account balance is ruppess',
            'profile': 'profile',
            'send money to': 'send money to',
            'say your name': 'say your name',
            'your transaction details': 'your transaction details',
            'write your pin': 'write your pin',
            'login to check your balance': 'login to check your balance',
            'update': 'update',
            'edit': 'edit',
            'new': 'new',
            'transactions': 'transactions',
            'Received from': 'Received from',
            'Money sent to': 'Money sent to',
            'empty input': 'empty input',
            'Log out': 'Log Out',
            'you have logged out': 'you have logged out',
            'updated successfully': 'updated successfully',
            'Commands Guide': 'Commands Guide',
            'enter': 'enter',
            
            'Create Account': 'Create Account',
            'Enter amount': 'Enter amount',
            'Next': 'Next',
            'Already have an account?': 'Already have an account?',
            'How to use': 'How to use',
            'des1':
                'Long press on the mic icon with red circle on the bottom of screen.',
            'des2':
                'After long press you will hear an sound.After that sound say your command.',
            'des3':
                'After saying your command you will hear sound again.Ater that sound effect remove long press',
            'des4':
                'Ater removing finger from mic.If your command exits it will perform the action,If not Again repeat the above steps with different command'
          },
      
        'te_IN': {
           'Set Pin':'పిన్ సెట్ చేయండి',
          // kkkkk
          'Enter your 6 digits pin': 'మీ ఆరు అంకెల పిన్‌ను నమోదు చేయండి',
          'bank transfer': 'బ్యాంకు బదిలీ',
          'send to person': 'వ్యక్తికి పంపండి',
          'UPI': 'యు పి ఐ',
          'Transfer money':'డబ్బు బదిలీ చేయండి',
          'Account balance': 'ఖాతా నిలువ',
          'People': 'వ్యక్తులు',
          'Features': 'లక్షణాలు',
          'Featured':'లక్షణాలు',

          'Explore': 'అన్వేషించండి',
          'Flight Tickets': 'విమాన టికెట్లు',
          'Bus Tickets': 'బస్సు టిక్కెట్లు',
          'train ticket': 'రైలు టికెట్',
          'movie tickets': 'సినిమా టిక్కెట్లు',
          'event tickets': 'ఈవెంట్ టిక్కెట్లు',
          'hotels': 'హోటళ్ళు',
          'Toll': 'టోల్',
          'uber cabs': 'ఉబెర్ క్యాబ్‌లు',
          'tickets booking': 'టిక్కెట్లు బుకింగ్',
          'stocks and IPO': 'స్టాక్స్ మరియు IPO',
          'insurance': 'భీమా',
          'healthcare': 'ఆరోగ్య సంరక్షణ',
          'Travel': 'ప్రయాణం',
          'Promotions': 'ప్రమోషన్లు',
          'Rewards': 'బహుమతులు',
          'offers': 'ఆఫర్లు',
          'Step':'దశ',
          'refferals': 'రెఫరల్స్',
          'See all payment activities': 'అన్ని చెల్లింపు కార్యకలాపాలను చూడండి',
          'Invite your friends': 'మీ స్నేహితులను ఆహ్వానించండి',
          "Get ₹101 after each friend's first payment":
              "ప్రతి స్నేహితుని మొదటి చెల్లింపు తర్వాత 101 రూపాయలను పొందండి",
          'Invite': 'ఆహ్వానించండి',
          'All transcations': 'అన్ని లావాదేవీలు',
          'Paying to': 'కు చెల్లిస్తోంది',
          'Pay to':"చెల్లించాలి",
          'Paid to' :'కు చెల్లించారు',
          'Recevied to you':'మీకు అందింది',
          'What is this for?': 'ఇది ఎందుకు?',
          'Tap to speak'.tr: 'మాట్లాడటానికి నొక్కండి',
          'You earned rupees 10 Cashback':
              'మీరు 10 రూపాయల క్యాష్‌బ్యాక్ పొందారు',
          'scratch the above card for your reward':
              'మీ రివార్డ్ కోసం పై కార్డ్‌ని స్క్రాచ్ చేయండి',
          'payment successful': 'చెల్లింపు విజయవంతమైంది',
          'done': 'సరే',
          'say hello': 'హలో చెప్పండి',
          'Pay': 'చెల్లించండి',
          'write to UPI': 'UPIకి వ్రాయండి',
          'Account': 'ఖాతా',
          'signed in as': 'ఇలా సైన్ ఇన్ చేసారు:',
          'mobile number': 'మొబైల్ నంబర్',
          'Payment methods': 'చెల్లింపు పద్ధతులు',
          'language': 'భాష',
          'app theme': 'యాప్ థీమ్',
          'privacy and security': 'గోప్యత మరియు భద్రత',
          'Privacy': 'గోప్యత',
          'notifications': 'నోటిఫికేషన్లు',
          'security': 'భద్రత',
          'Google pin': 'Google పిన్',
          'log out': 'లాగ్ అవుట్',
          'log out from Rp bank': 'Rp బ్యాంక్ నుండి లాగ్ అవుట్ అవ్వండి',
          'close account': 'ఖాతాను మూసివేయండి',
          'clear rp bank profile on this device':
              'ఈ పరికరంలో rp బ్యాంక్ ప్రొఫైల్‌ను క్లియర్ చేయండి',
          'information': 'సమాచారం',
          'help an feeback': 'సహాయం మరియు అభిప్రాయం',
          'raise BBPS dispute': 'BBPS వివాదాన్ని లేవనెత్తండి',
          "Personal Details":'వ్యక్తిగత వివరాలు',
          'Terms & privacy': 'నిబంధనలు & గోప్యత',
          'version 1.0.0': 'వెర్షన్ 1.0.0',
          'enter recipient name': 'గ్రహీత పేరు నమోదు చేయండి',
          'Recents': 'ఇటీవలివి',
          'success': 'విజయం',
          'money successfully sent to rahul':
              'డబ్బు విజయవంతంగా రాహుల్‌కు పంపబడింది',
          'profile': 'ప్రొఫైల్',
          'morning': 'శుభోదయం',
          'good afternoon': 'శుభ మద్యాహ్నం',
          'good evening': 'శుభ సాయంత్రం',

// kkkkk
          'your full name is': 'మీ పూర్తి పేరు',
          'enter': 'ఎంటర్',
          'transactions': 'లావాదేవీలు',
          'Send': 'పంపండి',
          'Login': "ప్రవేశించండి",
          "nick name": "మారుపేరు",
          "Good Morning": "శుభోదయం",
          "Good Afternoon": "శుభ మద్యాహ్నం",
          "Good Evening": "శుభ సాయంత్రం",
          "Send ": "పంపండి",
          'Request': 'అభ్యర్థన',
          "Don't have an account? ": "ఖాతా లేదా?",
          "Register": "నమోదు చేసుకోండి",
          "Enter 6 digits pin": "6 అంకెల పిన్‌ని నమోదు చేయండి",
          "Transactions": "లావాదేవీలు",
          "Enter nick name": "మారుపేరును నమోదు చేయండి",
          "Balance": "సంతులనం",
          "See More": "ఇంకా చూడండి",
          "Profile": "ప్రొఫైల్",
          "User Name": "వినియోగదారు పేరు",
          "Full Name": "పూర్తి పేరు",
          "U p i Id": "U p i Id",
          "Delete Account": "ఖాతాను తొలగించండి",
          "Enter Your Pin": "మీ పిన్‌ని నమోదు చేయండి",
          "Current Balance": "ప్రస్తుత నిల్వ",
          "enter upi id": "upi idని నమోదు చేయండి",
          "enter recevier name": "రిసీవియర్ పేరు నమోదు చేయండి",
          "selected language": "మీరు తెలుగును ఎంచుకున్నారు",
          "going to money sending page": "డబ్బు పంపే పేజీకి వెళుతోంది",
          'going to login page': "లాగిన్ పేజీకి వెళుతోంది",
          "going to back page": "పేజీ వెనుకకు వెళుతోంది",
          'going to register page': "నమోదు పేజీకి వెళుతోంది",
          'going to home page': 'హోమ్ పేజీకి వెళుతోంది',
          'going to profile page': "ప్రొఫైల్‌పేజీకి వెళుతోంది",
          'your personal details are': 'మీ వ్యక్తిగత వివరాలు',
          'Full Name': 'పూర్తి పేరు',
          'Mobile': 'మొబైల్',
          'Upi id': 'యూపీఐ ఐడి',
          'update profile': 'నవీకరణ',
          'Sorry command not recognized try again':
              "క్షమించండి ఆదేశం గుర్తించబడలేదు మళ్లీ ప్రయత్నించండి",
          'you have entered incorrect password':
              'మీరు తప్పు పాస్‌వర్డ్‌ని నమోదు చేసారు',
          "you are successfully logged in": "మీరు విజయవంతంగా లాగిన్ అయ్యారు",
          "Success": 'విజయం',
          'Failed': 'విఫలమైంది',
          'Incorrect Password': 'సరికాని పాస్వర్డ్',
          'No user Exits with nick name':
              'మారుపేరుతో వినియోగదారు నిష్క్రమించలేదు',
          'please check your pin': 'దయచేసి మీ పిన్‌ని తనిఖీ చేయండి',
          'your account balance is ruppess': 'మీ ఖాతా బ్యాలెన్స్ రూపాయలు',
          'profile': 'ప్రొఫైల్',
          'send money to': 'డబ్బు పంపండి',
          'say your name': 'మీ పేరు చెప్పండి',
          'write your pin': 'మీ పిన్ వ్రాయండి',
          'your transaction details': 'మీ లావాదేవీ వివరాలు',
          'login to check your balance':
              'మీ బ్యాలెన్స్ తనిఖీ చేయడానికి లాగిన్ చేయండి',
          'update': 'నవీకరణ',
          'edit': 'సవరించు',
          'new': 'కొత్త',
          'Received from': 'నుండి స్వీకరించబడింది',
          'Money sent to': 'డబ్బు పంపబడింది',
          'empty input': 'ఖాళీ ఇన్‌పుట్',
          'Log out': 'లాగ్ అవుట్',
          'you have logged out': 'మీరు లాగ్ అవుట్ చేసారు',
          'updated successfully': 'విజయవంతంగా నవీకరించబడింది',
          'Commands Guide': 'మార్గ దర్శకులు',
          'Create Account': 'ఖాతాను సృష్టించండి',
          'Next': 'తరువాత',
          "Enter amount": 'మొత్తాన్ని నమోదు చేయండి',
          'Already have an account?': 'ఖాతా కలిగి ఉన్నారా?',
          'How to use': 'ఎలా ఉపయోగించాలి',
          'des1':
              'స్క్రీన్ దిగువన ఎరుపు వృత్తంతో మైక్ చిహ్నంపై ఎక్కువసేపు నొక్కండి.',
          'des2':
              'ఎక్కువసేపు నొక్కిన తర్వాత మీకు శబ్దం వినబడుతుంది. ఆ ధ్వని తర్వాత మీ ఆదేశాన్ని చెప్పండి.',
          'des3':
              'మీ కమాండ్‌ని చెప్పిన తర్వాత మీకు మళ్లీ సౌండ్ వినబడుతుంది. ఆ సౌండ్ ఎఫెక్ట్ తర్వాత లాంగ్ ప్రెస్‌ని తీసివేయండి.',
          'des4':
              'ఆటర్ మైక్ నుండి వేలును తీసివేస్తుంది. మీ కమాండ్ నిష్క్రమిస్తే అది చర్యను అమలు చేస్తుంది, కాకపోతే మళ్లీ వేరే ఆదేశంతో పై దశలను పునరావృతం చేయండి.'
        }
      };
}
