import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_us': {
          'Login': "Login",
          'Send': 'Send',
          "nick name": 'nick name',
          "Good Morning": "Good Morning",
          "Good Afternoon": "Good Afternoon",
          "Good Evening": "Good evening",
          "Send ": "Send ",
          "Request": "Request",
          'Transactions': "Transactions",
          'Logout': "Logout",
          'Back': "Back ",
          "Don't have an account? ": "Don't have an account?",
          'enter amount here': "enter amount here",
          'Balance': "Balance",
          'pin number': "pin number",
          "Enter 6 digits pin": "Enter 6 digits pin",
          'pin': "pin",
          "Register": "Register",
          "Enter nick name": "Enter nick name",
          "See More": "See More",
          "Profile": "Profile",
          "User Name": "User Name",
          "Full Name": "Full Name",
          "Mobile": "Mobile",
          "Upi d": "Upi Id",
          "Delete Account": "Delete Account",
          "Enter Your Pin": "Enter Your Pin",
          "Current Balance": "Current Balance",
          "enter upi id": "enter upi id",
          "enter recevier name": "enter recevier name",
          "selected language": "you have selected english",
          "going to money sending page": "going to money sending page",
          "going to login page": 'going to login page',
          "going to back page": "going to back page",
          'going to register page': 'going to register page',
          'going to home page': 'going to home page',
          'going to profile page': 'going to profile page',
          'your personal details are': 'your personal details are',
          'user name': 'user name',
          'full name': 'full name',
          'mobile': 'mobile',
          'upi id': 'upi id',
          'update profile': 'update profile',
          'Sorry command not recognized try again':
              'Sorry command not recognized try again',
          'you have entered incorrect password':
              'you have entered incorrect password',
          "you are successfully logged in": 'you are successfully logged in',
          "Success": 'Success',
          'Failed': 'Failed',
          'Incorrect Password': 'Incorrect Password',
          'No user Exits with nick name': 'No user Exits with nick name',
          'please check your pin': 'please check your pin',
          'your account balance is ruppess': 'your account balance is ruppess',
          'profile': 'profile',
          'send money to': 'send money to',
          'say your name': 'say your name',
          'your transaction details': 'your transaction details',
          'write your pin': 'write your pin',
          'login to check your balance': 'login to check your balance',
          'update': 'update',
          'edit': 'edit',
          'new': 'new',
          'transactions': 'transactions',
          'Received from': 'Received from',
          'Money sent to': 'Money sent to',
          'empty input': 'empty input',
          'Log out': 'Log Out',
          'you have logged out': 'you have logged out',
          'updated successfully': 'updated successfully',
          'Commands Guide': 'Commands Guide',
          'enter':'enter',
           'To go to home page':'To go to home page : "Go to home page"',
             'To go to profile page':'To go to profile page : "profile page"',
             'To check balance':'To check balance : "check account balance"',
             'To send money':'To send money : "send money"',
              'To see history':'To see history : "show history"',
          'Create Account':'Create Account',
          'Next':'Next',
          'Already have an account?':'Already have an account?',
          'How to use':'How to use',
          'des1':'Long press on the mic icon with red circle on the bottom of screen.',
          'des2':'After long press you will hear an sound.After that sound say your command.',
          'des3':'After saying your command you will hear sound again.Ater that sound effect remove long press',
          'des4':'Ater removing finger from mic.If your command exits it will perform the action,If not Again repeat the above steps with different command'
        },
        'te_IN': {
          'enter':'ఎంటర్',
          'transactions': 'లావాదేవీలు',
          'Send': 'పంపండి',
          'Login': "ప్రవేశించండి",
          "nick name": "మారుపేరు",
          "Good Morning": "శుభోదయం",
          "Good Afternoon": "శుభ మద్యాహ్నం",
          "Good Evening": "శుభ సాయంత్రం",
          "Send ": "పంపండి",
          "Request": "అభ్యర్థన",
          "Don't have an account? ": "ఖాతా లేదా?",
          "Register": "నమోదు చేసుకోండి",
          "Enter 6 digits pin": "6 అంకెల పిన్‌ని నమోదు చేయండి",
          "Transactions": "లావాదేవీలు",
          "Enter nick name": "మారుపేరును నమోదు చేయండి",
          "Balance": "సంతులనం",
          "See More": "ఇంకా చూడండి",
          "Profile": "ప్రొఫైల్",
          "User Name": "వినియోగదారు పేరు",
          "Full Name": "పూర్తి పేరు",
          "Mobile": "మొబైల్",
          "U p i Id": "U p i Id",
          'write your pin': 'write your pin',
          "Delete Account": "ఖాతాను తొలగించండి",
          "Enter Your Pin": "మీ పిన్‌ని నమోదు చేయండి",
          "Current Balance": "ప్రస్తుత నిల్వ",
          "enter upi id": "upi idని నమోదు చేయండి",
          "enter recevier name": "రిసీవియర్ పేరు నమోదు చేయండి",
          "selected language": "మీరు తెలుగును ఎంచుకున్నారు",
          "going to money sending page": "డబ్బు పంపే పేజీకి వెళుతోంది",
          'going to login page': "లాగిన్ పేజీకి వెళుతోంది",
          "going to back page": "పేజీ వెనుకకు వెళుతోంది",
          'going to register page': "నమోదు పేజీకి వెళుతోంది",
          'going to home page': 'హోమ్ పేజీకి వెళుతోంది',
          'going to profile page': "ప్రొఫైల్‌పేజీకి వెళుతోంది",
          'your personal details are': 'మీ వ్యక్తిగత వివరాలు',
          'user name': 'వినియోగదారు పేరు',
          'full name': 'పూర్తి పేరు',
          'mobile': 'మొబైల్',
          'upi id': 'యూపీఐ ఐడి',
          'update profile': 'నవీకరణ',
          'Sorry command not recognized try again':
              "క్షమించండి ఆదేశం గుర్తించబడలేదు మళ్లీ ప్రయత్నించండి",
          'you have entered incorrect password':
              'మీరు తప్పు పాస్‌వర్డ్‌ని నమోదు చేసారు',
          "you are successfully logged in": "మీరు విజయవంతంగా లాగిన్ అయ్యారు",
          "Success": 'విజయం',
          'Failed': 'విఫలమైంది',
          'Incorrect Password': 'సరికాని పాస్వర్డ్',
          'No user Exits with nick name':
              'మారుపేరుతో వినియోగదారు నిష్క్రమించలేదు',
          'please check your pin': 'దయచేసి మీ పిన్‌ని తనిఖీ చేయండి',
          'your account balance is ruppess': 'మీ ఖాతా బ్యాలెన్స్ రూపాయలు',
          'profile': 'ప్రొఫైల్',
          'send money to': 'డబ్బు పంపండి',
          'say your name': 'మీ పేరు చెప్పండి',
          'write your pin': 'మీ పిన్ వ్రాయండి',
          'your transaction details': 'మీ లావాదేవీ వివరాలు',
          'login to check your balance':'మీ బ్యాలెన్స్ తనిఖీ చేయడానికి లాగిన్ చేయండి',
          'update': 'నవీకరణ',
          'edit': 'సవరించు',
          'new': 'కొత్త',
          'Received from': 'నుండి స్వీకరించబడింది',
          'Money sent to': 'డబ్బు పంపబడింది',
          'empty input': 'ఖాళీ ఇన్‌పుట్',
          'Log out': 'లాగ్ అవుట్',
          'you have logged out': 'మీరు లాగ్ అవుట్ చేసారు',
          'updated successfully': 'విజయవంతంగా నవీకరించబడింది',
          'Commands Guide': 'మార్గ దర్శకులు',
          'Create Account':'ఖాతాను సృష్టించండి',
          'Next':'తరువాత',
          'Already have an account?':'ఖాతా కలిగి ఉన్నారా?',
          'How to use':'ఎలా ఉపయోగించాలి',
          'des1':'స్క్రీన్ దిగువన ఎరుపు వృత్తంతో మైక్ చిహ్నంపై ఎక్కువసేపు నొక్కండి.',
          'des2':'ఎక్కువసేపు నొక్కిన తర్వాత మీకు శబ్దం వినబడుతుంది. ఆ ధ్వని తర్వాత మీ ఆదేశాన్ని చెప్పండి.',
          'des3':'మీ కమాండ్‌ని చెప్పిన తర్వాత మీకు మళ్లీ సౌండ్ వినబడుతుంది. ఆ సౌండ్ ఎఫెక్ట్ తర్వాత లాంగ్ ప్రెస్‌ని తీసివేయండి.',
          'des4':'ఆటర్ మైక్ నుండి వేలును తీసివేస్తుంది. మీ కమాండ్ నిష్క్రమిస్తే అది చర్యను అమలు చేస్తుంది, కాకపోతే మళ్లీ వేరే ఆదేశంతో పై దశలను పునరావృతం చేయండి.'
        }
      };
}
